//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace audiovisalParcial
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AUDIOVISUALESEntities : DbContext
    {
        public AUDIOVISUALESEntities()
            : base("name=AUDIOVISUALESEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<empleados> empleados { get; set; }
        public virtual DbSet<equipos> equipos { get; set; }
        public virtual DbSet<marcas> marcas { get; set; }
        public virtual DbSet<modelos> modelos { get; set; }
        public virtual DbSet<rentaDevolucion> rentaDevolucion { get; set; }
        public virtual DbSet<tecnologias_conexion> tecnologias_conexion { get; set; }
        public virtual DbSet<tipo_equipos> tipo_equipos { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
    }
}
