//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace audiovisalParcial
{
    using System;
    using System.Collections.Generic;
    
    public partial class rentaDevolucion
    {
        public int NoPrestamo { get; set; }
        public int Empleado { get; set; }
        public int Equipo { get; set; }
        public int Usuario { get; set; }
        public System.DateTime FechaPrestamo { get; set; }
        public Nullable<System.DateTime> FechaDevolucion { get; set; }
        public string Comentario { get; set; }
        public Nullable<int> Estado { get; set; }
    
        public virtual empleados empleados { get; set; }
        public virtual equipos equipos { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
