CREATE DATABASE AUDIOVISUALES;

USE AUDIOVISUALES;

CREATE TABLE tipo_equipos(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Descripcion VARCHAR(150) NOT NULL,
	Estado INT DEFAULT 1
)

CREATE TABLE marcas(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Descripcion VARCHAR(150) NOT NULL,
	Estado INT DEFAULT 1
)

CREATE TABLE modelos(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Marca INT NOT NULL,
	Descripcion VARCHAR(150) NOT NULL,
	Estado INT DEFAULT 1,
	FOREIGN KEY (marca) REFERENCES marcas (Id)
)

CREATE TABLE tecnologias_conexion(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Descripcion VARCHAR(150) NOT NULL,
	Estado INT DEFAULT 1
)

CREATE TABLE equipos(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Descripcion VARCHAR(150) NOT NULL,
	Noserial VARCHAR(50) NOT NULL,
	ServiceTag VARCHAR(50) NOT NULL,
	TipoEquipo INT NOT NULL,
	Marca INT NOT NULL,
	Modelo INT NOT NULL,
	TecnologiaConexion INT NOT NULL,
	Estado INT DEFAULT 1,
	FOREIGN KEY (TipoEquipo) REFERENCES tipo_equipos (Id),
	FOREIGN KEY (Marca) REFERENCES marcas (Id),
	FOREIGN KEY (Modelo) REFERENCES modelos (Id),
	FOREIGN KEY (TecnologiaConexion) REFERENCES tecnologias_conexion (Id)
)

CREATE TABLE usuarios(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Nombre VARCHAR(150) NOT NULL,
	Cedula VARCHAR(50) NOT NULL,
	NoCarnet VARCHAR(50) NOT NULL,
	TipoUsuario VARCHAR(50) NOT NULL,
	TipoPersona VARCHAR(50) NOT NULL,
	Estado INT DEFAULT 1
)

CREATE TABLE empleados(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Nombre VARCHAR(150) NOT NULL,
	Cedula VARCHAR(50) NOT NULL,
	TandaLabor VARCHAR(50) NOT NULL,
	FechaIngreso DATETIME DEFAULT getdate(),
	Estado INT DEFAULT 1
)

CREATE TABLE rentaDevolucion(
	NoPrestamo INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Empleado INT NOT NULL,
	Equipo INT NOT NULL,
	Usuario INT NOT NULL,
	FechaPrestamo DATETIME NOT NULL,
	FechaDevolucion DATETIME,
	Comentario VARCHAR(200),
	Estado INT DEFAULT 1,
	FOREIGN KEY (Empleado) REFERENCES empleados (Id),
	FOREIGN KEY (Equipo) REFERENCES equipos (Id),
	FOREIGN KEY (Usuario) REFERENCES usuarios (Id),
)