//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAudiovisuales
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AUDIOVISUALESEntities : DbContext
    {
        public AUDIOVISUALESEntities()
            : base("name=AUDIOVISUALESEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<empleado> empleados { get; set; }
        public virtual DbSet<equipos> equipos { get; set; }
        public virtual DbSet<marca> marcas { get; set; }
        public virtual DbSet<modelo> modelos { get; set; }
        public virtual DbSet<rentaDevolucion> rentaDevolucions { get; set; }
        public virtual DbSet<tecnologias_conexion> tecnologias_conexion { get; set; }
        public virtual DbSet<tipo_equipos> tipo_equipos { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
    }
}
