//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace audiovisalParcial.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equiment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equiment()
        {
            this.RentReturns = new HashSet<RentReturn>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string Serial { get; set; }
        public string ServiceTag { get; set; }
        public int EquimentTypesId { get; set; }
        public int BrandId { get; set; }
        public int ModelsId { get; set; }
        public int TechnologiesConnectionId { get; set; }
        public Nullable<int> StateId { get; set; }
        public bool Enabled { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual EquimentType EquimentType { get; set; }
        public virtual Model Model { get; set; }
        public virtual EquimentsState EquimentsState { get; set; }
        public virtual TechnologiesConnection TechnologiesConnection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentReturn> RentReturns { get; set; }
    }
}
