//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace audiovisalParcial.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equiments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equiments()
        {
            this.RentReturns = new HashSet<RentReturns>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string Serial { get; set; }
        public string ServiceTag { get; set; }
        public int EquimentTypesId { get; set; }
        public int BrandId { get; set; }
        public int ModelsId { get; set; }
        public int TechnologiesConnectionId { get; set; }
        public Nullable<int> StateId { get; set; }
        public bool Enabled { get; set; }
    
        public virtual Brands Brands { get; set; }
        public virtual EquimentTypes EquimentTypes { get; set; }
        public virtual Models Models { get; set; }
        public virtual EquimentsStates EquimentsStates { get; set; }
        public virtual TechnologiesConnections TechnologiesConnections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentReturns> RentReturns { get; set; }
    }
}
