//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace audiovisalParcial.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public equipos()
        {
            this.rentaDevolucions = new HashSet<rentaDevolucion>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public string Noserial { get; set; }
        public string ServiceTag { get; set; }
        public int TipoEquipo { get; set; }
        public int Marca { get; set; }
        public int Modelo { get; set; }
        public int TecnologiaConexion { get; set; }
        public Nullable<int> Estado { get; set; }
    
        public virtual marca marca1 { get; set; }
        public virtual modelo modelo1 { get; set; }
        public virtual tecnologias_conexion tecnologias_conexion { get; set; }
        public virtual tipo_equipos tipo_equipos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rentaDevolucion> rentaDevolucions { get; set; }
    }
}
