//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace audiovisalParcial.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AudiovisualDbEntities : DbContext
    {
        public AudiovisualDbEntities()
            : base("name=AudiovisualDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<BrandsState> BrandsStates { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeesState> EmployeesStates { get; set; }
        public virtual DbSet<Equiment> Equiments { get; set; }
        public virtual DbSet<EquimentsState> EquimentsStates { get; set; }
        public virtual DbSet<EquimentType> EquimentTypes { get; set; }
        public virtual DbSet<EquimentTypesState> EquimentTypesStates { get; set; }
        public virtual DbSet<Model> Models { get; set; }
        public virtual DbSet<ModelsState> ModelsStates { get; set; }
        public virtual DbSet<PersonalType> PersonalTypes { get; set; }
        public virtual DbSet<RentReturn> RentReturns { get; set; }
        public virtual DbSet<RentReturnState> RentReturnStates { get; set; }
        public virtual DbSet<TechnologiesConnection> TechnologiesConnections { get; set; }
        public virtual DbSet<TechnologiesConnectionState> TechnologiesConnectionStates { get; set; }
        public virtual DbSet<UserLogin> UserLogins { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UsersState> UsersStates { get; set; }
        public virtual DbSet<UsersType> UsersTypes { get; set; }
    }
}
