//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace audiovisalParcial.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AudiovisualDbEntities : DbContext
    {
        public AudiovisualDbEntities()
            : base("name=AudiovisualDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brands> Brands { get; set; }
        public virtual DbSet<BrandsStates> BrandsStates { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<EmployeesStates> EmployeesStates { get; set; }
        public virtual DbSet<Equiments> Equiments { get; set; }
        public virtual DbSet<EquimentsStates> EquimentsStates { get; set; }
        public virtual DbSet<EquimentTypes> EquimentTypes { get; set; }
        public virtual DbSet<EquimentTypesStates> EquimentTypesStates { get; set; }
        public virtual DbSet<Models> Models { get; set; }
        public virtual DbSet<ModelsStates> ModelsStates { get; set; }
        public virtual DbSet<PersonalTypes> PersonalTypes { get; set; }
        public virtual DbSet<RentReturns> RentReturns { get; set; }
        public virtual DbSet<RentReturnStates> RentReturnStates { get; set; }
        public virtual DbSet<TechnologiesConnections> TechnologiesConnections { get; set; }
        public virtual DbSet<TechnologiesConnectionStates> TechnologiesConnectionStates { get; set; }
        public virtual DbSet<UserLogins> UserLogins { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UsersStates> UsersStates { get; set; }
        public virtual DbSet<UsersTypes> UsersTypes { get; set; }
    }
}
