//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace audiovisalParcial.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentReturns
    {
        public int Id { get; set; }
        public string NoPay { get; set; }
        public int EmployeeId { get; set; }
        public int EquimentId { get; set; }
        public int UserId { get; set; }
        public System.DateTime LoanDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string Comentary { get; set; }
        public Nullable<int> StateId { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Equiments Equiments { get; set; }
        public virtual RentReturnStates RentReturnStates { get; set; }
        public virtual Users Users { get; set; }
    }
}
