//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace audiovisalParcial.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentReturn
    {
        public int Id { get; set; }
        public string NoPay { get; set; }
        public int EmployeeId { get; set; }
        public int EquimentId { get; set; }
        public int UserId { get; set; }
        public System.DateTime LoanDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string Comentary { get; set; }
        public Nullable<int> StateId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Equiment Equiment { get; set; }
        public virtual RentReturnState RentReturnState { get; set; }
        public virtual User User { get; set; }
    }
}
