//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace audiovisalParcial.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.RentReturns = new HashSet<RentReturn>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string IdentificationCard { get; set; }
        public string Carnet { get; set; }
        public Nullable<int> UsersTypesId { get; set; }
        public Nullable<int> PersonalTypesID { get; set; }
        public Nullable<int> StateId { get; set; }
        public bool Enabled { get; set; }
    
        public virtual PersonalType PersonalType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentReturn> RentReturns { get; set; }
        public virtual UsersState UsersState { get; set; }
        public virtual UsersType UsersType { get; set; }
    }
}
